const BANK_WITHDRAWAL_CHARGES = 10;
const CRYPTO_WITHDRAWAL_CHARGES = 5;
const ACCOUNT_NUMBER = "895556205";

module.exports = {
    BANK_WITHDRAWAL_CHARGES,
    CRYPTO_WITHDRAWAL_CHARGES,
    ACCOUNT_NUMBER
};
